In [2]:
!pip3 install numpy


[notice] A new release of pip is available: 23.2.1 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
import numpy as np

In [5]:
a = np.arange(6)

In [6]:
a

array([0, 1, 2, 3, 4, 5])

In [7]:
type(a)

numpy.ndarray

In [8]:
a[:]

array([0, 1, 2, 3, 4, 5])

In [10]:
a2 = a[np.newaxis, :]

In [15]:
a2.shape

(1, 6)

In [14]:
a.shape

(6,)

In [16]:
a = np.array([[1, 2, 3, 4], [5, 6,7, 8], [9, 10, 11, 12]])

In [17]:
print(a[0])

[1 2 3 4]


In [18]:
a = np.array([1,2,3])

In [19]:
np.zeros(2)

array([0., 0.])

In [20]:
np.ones(2)

array([1., 1.])

In [21]:
np.empty(2)

array([1., 1.])

In [22]:
np.arange(4)

array([0, 1, 2, 3])

In [23]:
np.arange(2, 9, 2)

array([2, 4, 6, 8])

In [24]:
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [25]:
x=np.ones(2, dtype=np.int64)
x

array([1, 1], dtype=int64)

In [31]:
arr = np.array([3,1,2,4,5,6,7,8])
arr

array([3, 1, 2, 4, 5, 6, 7, 8])

In [33]:
arr = np.sort(arr)
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [35]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
c = np.concatenate((a,b))
c

array([1, 2, 3, 4, 5, 6, 7, 8])

In [36]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

In [37]:
np.concatenate((x,y))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [38]:
x

array([[1, 2],
       [3, 4]])

In [39]:
y

array([[5, 6]])

In [40]:
np.concatenate((x,y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [42]:
array_example = np.array([[[0, 1, 2, 3], 
                           [4, 5, 6, 7]],
                          
                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])  

In [43]:
array_example.ndim

3

In [44]:
array_example.size

24

In [45]:
array_example.shape

(3, 2, 4)

In [48]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [52]:
b = a.reshape(2,3)
print(b)

[[0 1 2]
 [3 4 5]]


In [53]:
c = a.reshape(3,2)
print(c)

[[0 1]
 [2 3]
 [4 5]]


In [55]:
np.reshape(a, newshape=(1, 6), order='C')

array([[0, 1, 2, 3, 4, 5]])

In [57]:
a = np.array([1,2,3,4,5,6])
a.shape

(6,)

In [59]:
a2 = a[np.newaxis, :]
a2.shape

(1, 6)

In [60]:
a = np.array([1,2,3,4,5,6])
a.shape

(6,)

In [61]:
c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

In [62]:
data = np.array([1, 2, 3])
data

array([1, 2, 3])

In [63]:
data[1]

2

In [64]:
data[0:2]

array([1, 2])

In [65]:
data[:1]

array([1])

In [66]:
data[1:]

array([2, 3])

In [67]:
data[-2:]

array([2, 3])

In [68]:
a = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])

In [69]:
a<5

array([[ True,  True,  True,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [71]:
print(a [ a < 5 ])

[1 2 3 4]


In [72]:
five_up = (a>=5)

In [74]:
print(a[five_up])

[ 5  6  7  8  9 10 11 12]


In [75]:
divisible_by_2 = a[a%2==0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [76]:
c = a[(a>2) & (a<11)]
print(c)

[ 3  4  5  6  7  8  9 10]


In [81]:
a = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])

In [82]:
b = np.nonzero(a<5)
print(b)

(array([0, 0, 0, 0], dtype=int64), array([0, 1, 2, 3], dtype=int64))


In [83]:
list_of_coordinates = list(zip(b[0], b[1]))

In [84]:
for coord in list_of_coordinates:
    print(coord)

(0, 0)
(0, 1)
(0, 2)
(0, 3)


In [85]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [86]:
arr1 = a[3:8]

In [87]:
arr1

array([4, 5, 6, 7, 8])

In [88]:
a1 = np.array([[1, 1],
              [2, 2]])
a2 = np.array([[3, 3],
              [4, 4]])

In [89]:
np.vstack((a1, a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [90]:
np.concatenate((a1, a2), axis=0) 

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [94]:
np.concatenate((a1, a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [95]:
np.concatenate((a1, a2), axis=0)

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [93]:
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [96]:
x = np.arange(1, 25).reshape(2, 12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [97]:
np.hsplit(x,3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [98]:
np.hsplit(x, (3, 4))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

In [99]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [102]:
print(a[2, :])

[ 9 10 11 12]


In [103]:
print(a[:,2])

[ 3  7 11]


In [104]:
b = a[0,:]
b

array([1, 2, 3, 4])

In [105]:
b[0]=99

In [106]:
b

array([99,  2,  3,  4])

In [107]:
b2 = a.copy()
print(b2)

[[99  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [108]:
b2[1,1] = 7
b2

array([[99,  2,  3,  4],
       [ 5,  7,  7,  8],
       [ 9, 10, 11, 12]])

In [109]:
a

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [110]:
data = np.array([1, 2])

In [111]:
ones = np.ones(2, dtype = int)

In [117]:
data + ones

array([2, 3])

In [120]:
data-ones
data*ones
data/ones

array([1., 2.])

In [113]:
a = np.array([1, 2, 3, 4])

In [114]:
sum(a)

10

In [116]:
b = np.array([[1, 1],[2, 2]])
b.sum()

6

In [121]:
b.sum(axis=0) 

array([3, 3])

In [122]:
b.sum(axis=1)

array([2, 4])

In [123]:
data.max()

2

In [124]:
data.sum()

3

In [125]:
data.min()

1

In [126]:
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

In [127]:
a.sum()

4.8595784

In [128]:
a.min()

0.05093587

In [129]:
a.min(axis=0)

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

In [130]:
data = np.array([[1, 2], [3, 4], [5, 6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [131]:
data[0, 1]

2

In [132]:
data[1:3]

array([[3, 4],
       [5, 6]])

In [133]:
data[0:2, 0]

array([1, 3])

In [134]:
print(data.max())
print(data.min())
print(data.sum())

6
1
21


In [135]:
data = np.array([[1, 2], [5, 3], [4, 6]])
data

array([[1, 2],
       [5, 3],
       [4, 6]])

In [136]:
data.max(axis=0)

array([5, 6])

In [137]:
data.max(axis=1)

array([2, 5, 6])

In [138]:
data = np.array([[1, 2], [3, 4]])
ones = np.array([[1, 1], [1, 1]])
data + ones

array([[2, 3],
       [4, 5]])

In [139]:
data = np.array([[1, 2], [3, 4], [5, 6]])
ones_row = np.array([[1, 1]])
data + ones_row

array([[2, 3],
       [4, 5],
       [6, 7]])

In [140]:
data.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [141]:
data.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [142]:
arr = np.arange(6).reshape((2, 3))
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [143]:
arr.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

In [144]:
arr.T

array([[0, 3],
       [1, 4],
       [2, 5]])

In [145]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [148]:
reversed_arr = np.flip(arr)

In [149]:
print('Reversed Array: ', reversed_arr)

Reversed Array:  [8 7 6 5 4 3 2 1]


In [150]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [151]:
reversed_arr = np.flip(arr_2d)

In [152]:
reversed_arr_rows = np.flip(arr_2d, axis=0)
print(reversed_arr_rows)

[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [153]:
reversed_arr_columns = np.flip(arr_2d, axis=1)
print(reversed_arr_columns)

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]


In [154]:
arr_2d[:,1] = np.flip(arr_2d[:,1])
print(arr_2d)

[[ 1 10  3  4]
 [ 5  6  7  8]
 [ 9  2 11 12]]


In [155]:
x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [156]:
x.flatten() 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [157]:
a1 = x.flatten()

In [158]:
a1[0] = 99

In [159]:
print(x)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [160]:
print(a1)

[99  2  3  4  5  6  7  8  9 10 11 12]


In [161]:
a2 = x.ravel() 

In [162]:
a2[0] = 98

In [163]:
print(x)

[[98  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [164]:
print(a2)

[98  2  3  4  5  6  7  8  9 10 11 12]
